import React, { useState, useEffect } from 'react';
import { weaveContent, generateSocialImage } from '../services/geminiService';
import { LoomResult } from '../types';

export const TheLoom: React.FC = () => {
  const [goal, setGoal] = useState('');
  const [isWeaving, setIsWeaving] = useState(false);
  const [result, setResult] = useState<LoomResult | null>(null);
  const [systemContext, setSystemContext] = useState<any>({});

  // Simulate loading system context from "The Core" (Settings, Scribe, Stylist)
  useEffect(() => {
      // In a real app, these would come from a global store or Context API
      const dna = localStorage.getItem('elevate_brand_dna');
      const voice = localStorage.getItem('elevate_voice_fingerprint'); // Assuming Scribe saves here
      const style = localStorage.getItem('elevate_style_identity'); // Assuming Stylist saves here
      
      setSystemContext({
          voice: voice ? JSON.parse(voice) : null,
          style: style ? JSON.parse(style) : null,
          dna: dna ? JSON.parse(dna) : null
      });
  }, []);

  const handleWeave = async () => {
      if (!goal) return;
      setIsWeaving(true);
      setResult(null);
      
      // 1. Generate Strategy & Copy
      const loomResult = await weaveContent(goal, systemContext);
      
      if (loomResult) {
          // 2. Generate Visual (Parallel or Sequential)
          // We do it sequentially here to use the prompt generated by the Loom
          const imageUrl = await generateSocialImage(loomResult.visualPrompt, { aspectRatio: '1:1', highQuality: false });
          
          setResult({
              ...loomResult,
              generatedImageUrl: imageUrl || undefined
          });
      }
      setIsWeaving(false);
  };

  return (
    <div className="h-full flex flex-col gap-6">
       
       {/* Loom Header */}
       <div className="bg-surface rounded-xl border border-slate-700 p-8 flex flex-col items-center justify-center relative overflow-hidden">
            <div className="absolute inset-0 bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900"></div>
            <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/diagmonds-light.png')] opacity-10"></div>
            
            <div className="relative z-10 w-full max-w-2xl text-center">
                <h2 className="text-3xl font-light tracking-[0.2em] text-white mb-2 flex items-center justify-center gap-3">
                    <i className="fa-solid fa-scroll text-indigo-400"></i> THE LOOM
                </h2>
                <p className="text-indigo-200/60 font-mono text-xs uppercase tracking-widest mb-8">
                    Synthesizing Voice • Style • Strategy
                </p>

                <div className="flex gap-4 items-center bg-slate-900/50 p-2 rounded-full border border-slate-600">
                    <div className="flex-1">
                        <input 
                            type="text" 
                            value={goal}
                            onChange={(e) => setGoal(e.target.value)}
                            onKeyDown={(e) => e.key === 'Enter' && handleWeave()}
                            placeholder="What do you want to weave? (e.g. 'Announcement for new product launch')"
                            className="w-full bg-transparent text-white px-4 py-2 outline-none text-sm placeholder-slate-500"
                        />
                    </div>
                    <button 
                        onClick={handleWeave}
                        disabled={isWeaving || !goal}
                        className="bg-indigo-600 hover:bg-indigo-500 text-white rounded-full w-10 h-10 flex items-center justify-center shadow-lg transition-all disabled:opacity-50 disabled:scale-95"
                    >
                        {isWeaving ? <i className="fa-solid fa-circle-notch fa-spin"></i> : <i className="fa-solid fa-fingerprint"></i>}
                    </button>
                </div>

                {/* Connection Status Indicators */}
                <div className="flex justify-center gap-6 mt-6">
                    <div className={`flex items-center gap-2 text-xs ${systemContext.voice ? 'text-emerald-400' : 'text-slate-600'}`}>
                        <i className="fa-solid fa-microphone-lines"></i>
                        <span>{systemContext.voice ? 'Voice Active' : 'No Voice Data'}</span>
                    </div>
                    <div className={`flex items-center gap-2 text-xs ${systemContext.style ? 'text-purple-400' : 'text-slate-600'}`}>
                        <i className="fa-solid fa-palette"></i>
                        <span>{systemContext.style ? 'Style Active' : 'No Style Data'}</span>
                    </div>
                    <div className={`flex items-center gap-2 text-xs ${systemContext.dna ? 'text-blue-400' : 'text-slate-600'}`}>
                        <i className="fa-solid fa-dna"></i>
                        <span>{systemContext.dna ? 'Core Active' : 'No Core Data'}</span>
                    </div>
                </div>
            </div>
       </div>

       {/* Output Display */}
       <div className="flex-1 bg-slate-950 border border-slate-800 rounded-xl overflow-hidden relative flex flex-col md:flex-row">
            {!result ? (
                <div className="flex-1 flex flex-col items-center justify-center text-muted opacity-30">
                    <div className="relative">
                        <div className="absolute inset-0 bg-indigo-500 blur-3xl opacity-20"></div>
                        <i className="fa-brands fa-connectdevelop text-8xl relative z-10"></i>
                    </div>
                    <p className="mt-6 font-mono text-sm">Awaiting neural synthesis...</p>
                </div>
            ) : (
                <>
                    {/* Visual Side */}
                    <div className="w-full md:w-1/2 bg-black flex items-center justify-center relative border-r border-slate-800 p-8">
                        {result.generatedImageUrl ? (
                            <img src={result.generatedImageUrl} alt="Generated" className="max-w-full max-h-full shadow-2xl rounded-lg border border-white/10" />
                        ) : (
                            <div className="text-center">
                                <i className="fa-regular fa-image text-4xl text-slate-700 mb-2"></i>
                                <p className="text-xs text-slate-500">Visual generation failed or skipped.</p>
                            </div>
                        )}
                        <div className="absolute bottom-4 left-4 right-4 bg-black/80 backdrop-blur-md p-3 rounded border border-white/10">
                            <p className="text-[10px] text-slate-400 font-mono line-clamp-2">PROMPT: {result.visualPrompt}</p>
                        </div>
                    </div>

                    {/* Text Side */}
                    <div className="w-full md:w-1/2 flex flex-col bg-slate-900">
                        <div className="flex-1 overflow-y-auto p-8">
                            <div className="mb-6">
                                <h3 className="text-xs font-bold text-indigo-400 uppercase tracking-widest mb-4">Strategic Intent</h3>
                                <p className="text-sm text-slate-400 italic leading-relaxed border-l-2 border-indigo-500/50 pl-4">
                                    "{result.strategyReasoning}"
                                </p>
                            </div>

                            <div className="bg-surface border border-slate-700 rounded-xl p-6 shadow-xl">
                                <div className="flex items-center gap-3 mb-4">
                                    <div className="w-8 h-8 rounded-full bg-indigo-600"></div>
                                    <div className="h-2 w-24 bg-slate-700 rounded"></div>
                                </div>
                                <p className="text-slate-200 whitespace-pre-wrap leading-relaxed text-sm">
                                    {result.postCopy}
                                </p>
                                <div className="mt-4 flex flex-wrap gap-2">
                                    {result.hashtags.map((tag, i) => (
                                        <span key={i} className="text-indigo-400 text-xs">{tag}</span>
                                    ))}
                                </div>
                            </div>
                        </div>

                        <div className="p-6 border-t border-slate-800 flex justify-end gap-3 bg-slate-950">
                            <button className="px-4 py-2 text-xs font-bold text-slate-400 hover:text-white transition-colors">
                                Regenerate
                            </button>
                            <button className="px-6 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-xs font-bold shadow-lg transition-colors">
                                Schedule Post
                            </button>
                        </div>
                    </div>
                </>
            )}
       </div>
    </div>
  );
};